### ISSUE TITLE
Firebase auth properties are not updated on user profile change

### ISSUE THREAD

**Issue by lpellegr** [firebase/polymerfire#246]
### Description

Firebase auth properties are not updated when user data are changed following a call to `this.user.updateProfile`, `this.user.updateEmail`, etc.

### Expected outcome

Firebase auth properties value reflect the last changes.

### Actual outcome

Firebase auth properties value remains the same as before an update. A full page reload is required to get fresh values.

### Steps to reproduce

1. Make use of `firebase-auth` custom element:

```
<firebase-auth id="auth" user="{{user}}"></firebase-auth>
```

2. In your custom element template, display the user display name property value:

```
Username: [[user.displayName]]
```

3. Create an action (triggered for instance upon a tap on a button) that changes the current user display name as follows:

```
this.user.updateProfile({displayName: 'What a fail!'});
```

When the button is tapped, your page should display `Username: What a fail!` but it does not. The old value remains.

I was thinking about an something related to how [dirty checking](https://www.polymer-project.org/2.0/docs/devguide/data-system#mutable-data) is working with Polymer. As a consequence, I tried to force the update manually:

```
this.set('user.displayName', newFullName);
```

Unfortunately, this fails with the following error:

> Cannot assign to read only property 'displayName' of object...

Indeed, if I look at the implementation of `firebase-auth.html`, the property `user` is defined as `readOnly`.

I am still looking for a solution or a temporary workaround.

### Browsers Affected

- [x ] Chrome
- [x ] Firefox
- [x ] Safari 9
- [x ] Safari 8
- [x ] Safari 7
- [x ] Edge
- [x ] IE 11
- [x] IE 10

**Comment by lpellegr** [comment]
@e111077 @mbleigh Do you know if it is an expected behavior or a bug? do you know a workaround that does not require to reload the full page?

**Comment by tjmonsi** [comment]
Have you checked the new value of this.user.displayName. If it did changed then I guess you just need to propagate the change?

**Comment by lpellegr** [comment]
@tjmonsi If I look at the value after the change has been performed using the debug mode or by printing with console.log, I see the new content. However, the content is not updated where the data binding `[[user.displayName]]` is used. I tried to use notifyPath, etc. with no success.

**Comment by lpellegr** [comment]
@tjmonsi What is your suggestion to propagate the change?

**Comment by mbleigh** [comment]
This is expected. Firebase Auth data is not synced in real time. There may
be a way to force it to fetch, but I'm not sure off of the top of my head.

**Comment by tjmonsi** [comment]
@lpellegr would it be better to do this?
```
<firebase-auth id="auth" user="{{user}}"></firebase-auth>

this.$.auth.user.updateProfile({displayName: 'What a fail!'});
```

then see if this.$.auth.user changes

**Comment by lpellegr** [comment]
@tjmonsi I tried but I have the same issue as when I use `this.user`.

@mbleigh Do you know where I can find the information to force a fetch?

I have tried [reload](https://firebase.google.com/docs/reference/js/firebase.User#reload) with no success.

**Comment by lpellegr** [comment]
@tjmonsi @mbleigh I have created a minimal example that reproduces the issue:

You can try by using _test@test.com_ as email and _testing_ as password.

The source code is available below:

https://github.com/lpellegr/polymerfire-issue-246

**Comment by tjmonsi** [comment]
I'll try check this in a bit. Thanks for the repo.

**Comment by tjmonsi** [comment]
I have tried doing a notifyPath and it works. Please check my fork at https://github.com/tjmonsi/polymerfire-issue-246

**Comment by lpellegr** [comment]
@tjmonsi Thanks a lot, this is a solution. 

However, it looks like against the encapsulation of web components. You need to bind the same property with all components that need the information for something that firebase-auth component has the hand on. Don't you think firebase-auth should trigger a notifyPath on its own?

**Comment by tjmonsi** [comment]
Well that can be done, that is if firebase-auth has a method that allows updateProfile, then do a notifyPath to displayName and photoUrl. The only problem is when you have two firebase-auth elements. If you do an updateProfile on one element, the other will not be able to see that the displayName has been changed

**Comment by phidias51** [comment]
Since virtually every application has a user profile, wouldn't it make sense for a developer to be able to configure the database to point to a user profile?  Imagine if you had a getProfile, and setProfile methods, and a way within the config to say "pathToUserProfile="/user/{{user.uid}}" is where the profile is located.  This could give you a consistent approach to getting and setting user profile information, and would take care of automatically creating a profile, whenever the user logs in the first time.  This would give developers the ability to focus more of their time on their app, and less on the "busy work" required for most user-centric apps.

**Comment by mbleigh** [comment]
@phidias51 I would encourage you to explore building your own elements to do something along those lines. For PolymerFire, the goal is to expose the primitives of the Firebase SDKs in a friendly-to-consume format for Polymer developers. Getting opinionated about app structure is beyond the scope of this library.

**Comment by Al-bukair** [comment]
Any solution yet?

**Comment by exzizt** [comment]
I believe this is still an issue.

I have authenticated using Google Play Games. I have a message in my game that says, "Welcome <FirebaseAuth.CurrentUser.DisplayName>!" (essentially that). When I change the name of this user in their Google Play Games profile, subsequent plays of the game (it has now been over a week) still display the user's old display name.

I have tried using "FirebaseAuth.CurrentUser.ReloadAsync()" and that doesn't seem to have "refreshed" the user's details as it is [documented](https://firebase.google.com/docs/reference/unity/class/firebase/auth/firebase-user?authuser=0&hl=th#class_firebase_1_1_auth_1_1_firebase_user_1a0b3aa0fa399fb2fc7e2ebc2ff8926c31) to do.

I will try some more playing around and edit my post here if I find anything.

**Comment by diego-lipinski-de-castro** [comment]
Does is happening when you use Firebase with Flutter, im having this problema right now. I update the user number profile, and I need a full reload to get it into the app, THIS IS REALLY ANNOYING.
Its over ONE year and nothing yet?????

**Comment by tomCarnevale** [comment]
I'm having this issue using firebase authentication in unity as well. My email at my new job spelled my name wrong, so i fixed it. But when i authenticate with firebase using my work email, and I check my name via `FirebaseAuth.CurrentUser.DisplayName`, the name appears as the misspelled version. Checking my google account, everything is using my correctly spelled name. Is there perhaps a separate account I need to update that firebase is using?

**Comment by harisraharjo** [comment]
I'm having this issue when checking is user email verified or not using redux saga and react (I didn't use observer method). Any updates?

**Comment by GuilhermeLeivas** [comment]
Is there a final solution for this issue ?

**Comment by calebbarton1** [comment]
We are also having this problem on our product. Users who create an account are directed to a name change screen, which goes through fine. We can see when exporting our firebase users that this display name goes through correctly. 
However the display name change doesn't reflect in the FirebaseAuth.DefaultInstance.CurrentUser.DisplayName until the app is restarted. Using CurrentUser.ReloadAsync() does not update the display name either.

**Comment by ChARCOOL** [comment]
Holy moly dude, this bug still exists in Jan 19, 2021, unbelievable.

**Comment by ashcrok** [comment]
Indeed, can confirm. On Jan 21, 2021, still an issue. Wowza!

**Comment by samtstern** [comment]
@ChARCOOL @ashcrok unfortunately this will be an issue in 2022 as well ... to quote the README

> This library is no longer actively maintained. We do not recommend using this library in production.
> 
> If you maintain a fork of this library that you believe is healthier than the official version, we may consider recommending your fork. Please open a Pull Request if you believe that is the case.

I don't mean to come off as harsh but I want to set your expectations properly. You should not use polymerfire and you should not expect it to improve. There are likely other good Firebase+Polymer libraries out there but this isn't one of them.

**Comment by ashcrok** [comment]
> @ChARCOOL @ashcrok unfortunately this will be an issue in 2022 as well ... to quote the README
> 
> > This library is no longer actively maintained. We do not recommend using this library in production.
> > If you maintain a fork of this library that you believe is healthier than the official version, we may consider recommending your fork. Please open a Pull Request if you believe that is the case.
> 
> I don't mean to come off as harsh but I want to set your expectations properly. You should not use polymerfire and you should not expect it to improve. There are likely other good Firebase+Polymer libraries out there but this isn't one of them.

You are completely right. I missed that info in the README. Thanks for the prompt response.
